# Render manifest: deploy both frontend and backend as Docker web services
services:
  - type: web_service
    name: gov-project
    repo: https://github.com/chandan01245/mgnrega-karnataka # replace with your repo URL or leave for Render UI
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    context: .
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "postgresql://mgnrega_db_cwqx_user:XxgtCpwfMCITwysrifK0t8MmJtCL1hVZ@dpg-d427c4be5dus73bg9n7g-a/mgnrega_db_cwqx" # replace with your DB connection
      - key: REACT_APP_BACKEND_URL
        value: "http://127.0.0.1:8000/" # Adjust in Render dashboard after deploy if needed

# Usage notes:
# - Update repo, envVars and any plan/instance changes via the Render UI or by editing this file.
# - After deploying, set the frontend's REACT_APP_BACKEND_URL to the backend service URL Render shows.
# Notes:
# - Update the REACT_APP_BACKEND_URL value to the backend service URL that Render assigns once deployed.
# - If you prefer to deploy frontend as a web_service instead of static_site (e.g., using Docker), change `type` to `web_service` and provide a Dockerfile or build/start commands.
# - Review and adjust plans, instance types, and environment variables in the Render UI as needed.
